// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ7bPh1AWOrCf2xZ8Uh0w478yHzPw_O2s',
    appId: '1:810648563142:web:d2df50c177abbfe0bc16c7',
    messagingSenderId: '810648563142',
    projectId: 'kurumostateful',
    authDomain: 'kurumostateful.firebaseapp.com',
    storageBucket: 'kurumostateful.appspot.com',
    measurementId: 'G-Q91F2CXW06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMimMLf5vGvYAEI0fo2fwdgQxivzeY-Gk',
    appId: '1:810648563142:android:70878ea961959d23bc16c7',
    messagingSenderId: '810648563142',
    projectId: 'kurumostateful',
    storageBucket: 'kurumostateful.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAweScmnClYfT2VDqmEE6sKUGaSR5sYdP8',
    appId: '1:810648563142:ios:2f385b82cb1e33cbbc16c7',
    messagingSenderId: '810648563142',
    projectId: 'kurumostateful',
    storageBucket: 'kurumostateful.appspot.com',
    iosClientId: '810648563142-qog8lukvs55kg0anb5hba713t5oadc9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.kurumoStateful',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAweScmnClYfT2VDqmEE6sKUGaSR5sYdP8',
    appId: '1:810648563142:ios:25a87c85b7a08195bc16c7',
    messagingSenderId: '810648563142',
    projectId: 'kurumostateful',
    storageBucket: 'kurumostateful.appspot.com',
    iosClientId: '810648563142-borg0f7lujmu8jr0ate4mmg5jo5mu7gd.apps.googleusercontent.com',
    iosBundleId: 'com.example.kurumoStateful.RunnerTests',
  );
}
